version: '3.1'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: your-database
      POSTGRES_USER: your-username
      POSTGRES_PASSWORD: your-password
    ports:
      - "5432:5432"
